language: php

php:
  - 5.6
  - 7.0
  - 7.1

install: composer update

before_script: sudo redis-server /etc/redis/redis.conf --port 6379

notifications:
  email:
    recipients: kontakt@daniel-kahl.de
    on_success: change
    on_failure: change